# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2a8e453a7cd1ea8f11d96d5a27c71fe9e7154239a6dc2edfa1c809fbb4392b0240e6d8a7139c8a02629f790f82c3fd6cd26cf51d168c0cd1314afa12d282fe1
  api_key: 7878d6bbe010dc9a2fa5160aa7fccdef

test:
  secret_key_base: e0f3693d37216abc1d9bfde933171e36506503499260dfeded1e08ca268750cb5b44ad402a635196e78d4ed0c53bf3308492e98987b9c04969c33feb22ea24dc
  api_key: 7878d6bbe010dc9a2fa5160aa7fccdef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_key: 7878d6bbe010dc9a2fa5160aa7fccdef
